### ISSUE TITLE
Move a copy of React Native Storybook

### ISSUE THREAD

**Issue by mnmtanish** [storybooks/mono#9]
I think it's a good idea to move a copy of React Native Storybook to this repo as early as possible. If we decide to go ahead with the mono-repo approach, I believe having RNSB here early will help us make better decisions.

cc @ndelangen

**Comment by ndelangen** [comment]
1. All the repo's will be merged into this one.
2. Then we replace the react-storybook repo with this one (preserving github stars ✨) 
3. Then we move over all the issues from all repo's.
4. Then we close all the other repo's.

Merging in another repo is manual work I do. I do it in a way that allows me to keep everything up to date up to the last moment.
